version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ultimaitech_postgres_prod
    environment:
      POSTGRES_DB: ultimaitech_portfolio
      POSTGRES_USER: ultimaitech_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ultimaitech_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ultimaitech_network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: ultimaitech_backend_prod
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
      PORT: 5001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ultimaitech_portfolio
      DB_USER: ultimaitech_user
      DB_PASSWORD: ${POSTGRES_PASSWORD:-ultimaitech_password}
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_here}
      UPLOAD_PATH: /app/uploads
      FRONTEND_URL: https://ultimaitech.com,https://www.ultimaitech.com
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - ultimaitech_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ultimaitech_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Frontend/dist:/usr/share/nginx/html
      - ./nginx.fullstack.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
      - ./uploads:/usr/share/nginx/uploads
    depends_on:
      - backend
    networks:
      - ultimaitech_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  ultimaitech_network:
    driver: bridge
